### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by VaclavElias** [VaclavElias/stride#7]
Great questions! Here are practical recommendations for the scenarios you described:

---

### 1. **Restricting Workflow Runs to Prevent Abuse & Save Minutes**

**Problem:**  
By default, workflows triggered by PRs (e.g., `pull_request`, `pull_request_target`) can run for any PR—even from forks. This can be abused, burning through free GitHub Actions minutes.

**Common Strategies:**

#### a) **Using `pull_request_target` for Control**

- `pull_request_target` runs in the context of the base repository (with secrets) even for PRs from forks.
- Combine with a conditional in your workflow to only proceed if the PR is from a trusted user or org.

```yaml
# .github/workflows/your-workflow.yml
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  check-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Author
        if: github.event.pull_request.user.login == 'trusted-user' || contains(fromJson('["user1","user2"]'), github.event.pull_request.user.login)
        run: echo 'This PR is from a trusted user'
```

But **hardcoding users is rarely scalable**.

#### b) **Check Organization Membership in the Workflow**

You can use the [actions/github-script](https://github.com/actions/github-script) action to check if the PR author is a member of your org:

```yaml
- uses: actions/github-script@v7
  id: check_member
  with:
    script: |
      const { data: membership } = await github.orgs.getMembershipForUser({
        org: 'stride3d',
        username: context.payload.pull_request.user.login
      }).catch(e => ({ data: null }));
      core.setOutput('is_member', !!membership);
- name: Continue if org member
  if: steps.check_member.outputs.is_member == 'true'
  run: echo "User is org member, continuing workflow"
```

#### c) **Require Manual Trigger via PR Comment**

You can use a [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) with a GitHub App/bot (e.g., [peter-evans/slash-command-dispatch](https://github.com/peter-evans/slash-command-dispatch)) to only run jobs when a specific comment is made by an org member.

- Configure the action to listen for `/run-ci` (or similar) comments.
- In the workflow, check the comment author is a member of your org (similar to above).
- Only proceed if they are.

#### d) **Limit Workflow Runs to Specific Branches**

If only trusted contributors can push branches to the main repo, limit triggers to those branches, not forks:

```yaml
on:
  pull_request:
    branches:
      - main
      - release/*
```

---

### 2. **Do .NET Foundation Projects Get More Free Minutes?**

As of now, public repositories get unlimited free minutes on GitHub Actions. For private repos, organizations on a sponsored plan (e.g., .NET Foundation) may get more minutes or storage, but **you should confirm with the .NET Foundation directly or your repo admin**.  
Reference: [GitHub Actions usage limits](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#usage-limits)

---

### 3. **Triggering Workflows by Comment or Button**

- **By Comment:** See [peter-evans/slash-command-dispatch](https://github.com/peter-evans/slash-command-dispatch) or [github-actions[bot]/action-comment-run](https://github.com/github-actions[bot]/action-comment-run).
- **By Button:** Not possible natively, but a GitHub App or bot could provide this via an external dashboard. Otherwise, use [workflow_dispatch] for manual runs with restricted access.

---

## **Recommended Approach for Your Use Case**

- Use `pull_request_target` but in the first job, check that the PR author is a member of your org (as shown above).
- Or, require a `/run-tests` comment from an org member to trigger the expensive workflows.
- Use [peter-evans/slash-command-dispatch](https://github.com/peter-evans/slash-command-dispatch) for comment triggers.

---

**Summary Table:**

| Restriction Method              | Effort | Security | Usability | Notes                                        |
|---------------------------------|--------|----------|-----------|----------------------------------------------|
| Org membership check in YAML    | Low    | High     | Med       | Requires a simple script in workflow         |
| Comment-based trigger           | Med    | High     | High      | Requires bot/app, more user-friendly         |
| Limit branches                  | Low    | Med      | Med       | Only useful if contributors can't push forks |

---

Let me know if you'd like an example workflow for any of these approaches!
